const cardList = [
  {
    description: "Test Automation",
    bkgImgClass: "bkg-img-sdet",

    icons: [
      "cucumber-plain.svg",
      "icons8-selenium.svg",
      "icon-junit_bkg.svg",
      "playwright.svg",
      "jenkins-color.svg",
      "icon-mockito_bkg.svg",
      "icon-testng_bkg.svg",
      "icon-cypress.svg",
    ],
    backList: [
      "Cucumber",
      "Selenium",
      "JUnit",
      "Restassured",
      "Playwright",
      "Jenkins",
      "Mockito",
      "TestNG",
      "Cypress",
    ],
  },
  {
    description: "Development",
    bkgImgClass: "bkg-img-dev",
    icons: [
      "icons8-java.svg",
      "icons8-python.svg",
      "icons8-html-5.svg",
      "icons8-css3.svg",
      "icons8-javascript.svg",
      "icons8-sass.svg",
      "icons8-spring-logo.svg",
      "nextjs-original.svg",
      "icons8-react.svg",
      "icons8-github.svg",
    ],
    backList: [
      "Java",
      "Python",
      "HTML",
      "CSS",
      "JavaScript",
      "Sass",
      "Spring",
      "NextJS",
      "React",
      "Git",
    ],
  },
  {
    description: "Creative",
    bkgImgClass: "bkg-img-creative",
    icons: [
      "icons8-adobe-photoshop.svg",
      "icons8-adobe-illustrator.svg",
      "icons8-autodesk-maya.svg",
      "icons8-zbrush.svg",
      "icons8-figma.svg",
      "icons8-adobe-after-effects.svg",
      "icon-ca.svg",
      "icon-premierp.svg",
    ],
    backList: [
      "Photoshop",
      "Illustrator",
      "Maya",
      "Zbrush",
      "Figma",
      "After Effects",
      "Character Animator",
      "Premiere Pro",
    ],
  },
];

export default cardList;
